/*
Copyright 2023 c-fraser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by https://github.com/Kotlin/kotlinx-knit. DO NOT EDIT.
package io.github.cfraser.graphguard.knit

import io.github.cfraser.graphguard.Server
import io.github.cfraser.graphguard.plugin.Script
import io.github.cfraser.graphguard.runMoviesQueries
import io.github.cfraser.graphguard.withNeo4j
import java.net.URI
import kotlin.concurrent.thread

fun runExample05() {
  withNeo4j {

val script = """
import java.util.concurrent.atomic.AtomicInteger

plugin { 
  val messages = AtomicInteger()
  intercept { message ->
    if (messages.getAndIncrement() == 0) println(message::class.simpleName)
    message
  }
}
"""
val proxy = thread {
  try {
    Server(URI(boltUrl), Script.evaluate(script)).run()
  } catch (_: InterruptedException) {}
}
Thread.sleep(10_000) // Wait for the proxy server to initialize
runMoviesQueries(adminPassword)
proxy.interrupt()
  }
}
