/*
Copyright 2023 c-fraser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by https://github.com/Kotlin/kotlinx-knit. DO NOT EDIT.
package io.github.cfraser.graphguard.knit

import io.github.cfraser.graphguard.Schema
import io.github.cfraser.graphguard.Server
import io.github.cfraser.graphguard.withNeo4j
import org.neo4j.driver.AuthTokens
import org.neo4j.driver.GraphDatabase
import org.neo4j.driver.exceptions.DatabaseException
import java.net.URI
import kotlin.concurrent.thread
import kotlin.time.Duration.Companion.seconds

fun runExample02() {
  withNeo4j {

val proxy = thread {
  try {
    Server.create("localhost", 8787, URI(boltUrl), Schema.parse(MOVIES_SCHEMA)).run()
  } catch (_: InterruptedException) {}
}
Thread.sleep(3.seconds.inWholeMilliseconds) // Wait for the proxy server to initialize
GraphDatabase.driver("bolt://localhost:8787", AuthTokens.basic("neo4j", adminPassword)).use { driver ->
  driver.session().use { session ->
    /** Run *this* invalid query and print the schema violation message. */
    fun String.run() {
      try {
        session.run(this)
        error("Expected schema violation for query '$this'")
      } catch (exception: DatabaseException) {
        println(exception.message)
      }
    }
    "CREATE (:TVShow {title: 'The Office', released: 2005})".run()
    "MATCH (theMatrix:Movie {title: 'The Matrix'}) SET theMatrix.budget = 63000000".run()
    "MERGE (:Person {name: 'Chris Fraser'})-[:WATCHED]->(:Movie {title: 'The Matrix'})".run()
    "MATCH (:Person)-[produced:PRODUCED]->(:Movie {title: 'The Matrix'}) SET produced.company = 'Warner Bros.'".run()
    "CREATE (Keanu:Person {name: 'Keanu Reeves', born: '09/02/1964'})".run()
  }
}
proxy.interrupt()
  }
}
