/*
Copyright 2023 c-fraser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by https://github.com/Kotlin/kotlinx-knit. DO NOT EDIT.
package ${test.package}

import io.github.cfraser.graphguard.LOCAL
import io.kotest.core.spec.style.FunSpec
import kotlinx.knit.test.captureOutput
import kotlinx.knit.test.verifyOutputLines

class ${test.name} : FunSpec() {

  init {
    tags(LOCAL)
<#list cases as case><#assign method = test["mode.${case.param}"]!"custom">
    test("${case.name}") {
    captureOutput("${case.name}") { ${case.knit.package}.run${case.knit.name}() }<#if method != "custom">.${method}(
    <#list case.lines as line>
        "${line?j_string}"<#sep>,</#sep>
    </#list>
  )
<#else>.also { lines ->
  check(${case.param})
  }
</#if>
    }
    <#sep>

</#list>
  }
}