[versions]
knit = "0.5.0"
kotest = "5.9.1"
kotlin = "2.0.0"
kotlinx-coroutines = "1.8.0"
ktfmt = "0.50"
ktor = "2.3.10"
slf4j = "2.0.12"

[libraries]
antlr4 = { module = "org.antlr:antlr4", version = "4.13.1" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.8" }
clikt = { module = "com.github.ajalt.clikt:clikt-jvm", version = "4.4.0" }
jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version = "2.17.1" }
knit = { module = "org.jetbrains.kotlinx:kotlinx-knit", version.ref = "knit" }
knit-test = { module = "org.jetbrains.kotlinx:kotlinx-knit-test", version.ref = "knit" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest-jvm", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.6" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "7.4" }
mordant = { module = "com.github.ajalt.mordant:mordant-jvm", version = "2.2.0" }
neo4j-cypher-parser = { module = "org.neo4j:neo4j-cypher-dsl-parser", version = "2024.0.1" }
neo4j-java-driver = { module = "org.neo4j.driver:neo4j-java-driver", version = "5.21.0" }
neo4j-test-harness = { module = "org.neo4j.test:neo4j-harness", version = "5.20.0" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.13.2" }
dependency-versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
jreleaser = { id = "org.jreleaser", version = "1.12.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.8.1" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
