/*
Copyright 2023 c-fraser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by https://github.com/Kotlin/kotlinx-knit. DO NOT EDIT.
package io.github.cfraser.graphguard.knit

/** The schema DSL for the *movies* graph. */
const val MOVIES_SCHEMA =
    """

graph Movies {
  node Person(name: String, born: Integer):
      ACTED_IN(roles: List<String>) -> Movie,
      DIRECTED -> Movie,
      PRODUCED -> Movie,
      WROTE -> Movie,
      REVIEWED(summary: String, rating: Integer) -> Movie;

  node Movie(title: String, released: Integer, tagline: String);
}
"""
